name: Continuous Integration

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Build image
        run: docker-compose -f docker-compose.yml build
        
        
